name: crossdart
version: 0.4.6
author: Anton Astashov <anton.astashov@gmail.com>
description:
  Generates crossdart.info content.
  Also, allows to generate metadata for the project, and then use
  the Chrome Extension to add links to the declarations
  on Github
homepage: https://www.crossdart.info
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  pub_semver: 1.4.2
  intl: any
  package_config: any
  args: any
  collection: any
  resource: any
  logging: any
  yaml: any
  http: any
  # bad Erroneous...
  # analyzer: 0.32.4
  # bad pub_package_map_provider.dart missing
  # analyzer: 0.33.0
  analyzer: 0.39.2+1

dev_dependencies:
  test: any
